### PR TITLE
Fix gi module not found on F30

### PR DESCRIPTION
**Pull request by mikedep333**
Also, comment updates and yamllint/ansible-lint fixes.

### CODE REVIEW

**Review by bmbouter — APPROVED** [review]
This looks good to me. Thanks @mikedep333 !

**Comment by bmbouter** [comment]
@mikedep333 should I push this to Galaxy?

**Comment by mikedep333** [comment]
@bmbouter Yes

**Comment by bmbouter** [comment]
@mikedep333 done https://galaxy.ansible.com/pulp/pulp_rpm_prerequisites

**Pull request merged**
