### PR TITLE
[noissue]: Add missing RPM for successful rpm build to CentOS vars

### PR DESCRIPTION
**Pull request by makesse**

### CODE REVIEW

**Comment by yogev-lb** [comment]
@makesse hello. when can we expect this to be merged to master?
it fix the build on CentOS7.6 and i don't see the harm in merging it

**Comment by makesse** [comment]
@yogev-lb : I do not have write access, so I am not allowed to merge this PR. Let me see if I can find out who can assist me here.

**Comment by mikedep333** [comment]
Sorry for not noticing this earlier.

I will request write access, and try to monitor this repo better.

I already implemented this in 7d212e3e5d126072923d63d9ec79309f43a73ee7 , which was merged by someone with write access.

**Comment by makesse** [comment]
@mikedep333 : thank you! I will close this PR.

**Pull request closed without merging**
